### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-wallet#1]
## `@todo`
* [ ] [`datdot-wallet#2` improve wallet ui](https://github.com/playproject-io/datdot-wallet/issues/2)
* [ ] integrate wallet with node and vault
* [ ] include https://github.com/playproject-io/wallet/
* [ ] include https://github.com/playproject-io/wallet-data/
* [ ] include https://github.com/playproject-io/wallet-simulator

---
